### PR TITLE
Dockerfiles for Alpine 3.8/edge build with Nginx 1.14/1.15 (stable/ma…

### LINKED ISSUE #1181: Support Alpine
The direction is going towards using Docker, and on Docker the direction is towards using Alpine base images (because they're smaller), and most main packages now support Alpine (Nginx included).

It seems that it almost compiles on `alpine:edge`. I got past the traceback by installing `libunwind@testing` package but some missing references remain:

```
psol/lib/Release/linux/x64/pagespeed_automatic.a(1.time.o.o): In function `base::Time::FromDoubleT(dtime.cc:(.text._ZN4base4Time11FromDoubleTEd+0x2a): undefined reference to `__isnan'
psol/lib/Release/linux/x64/pagespeed_automatic.a(96.string_util.o.o): In function `net_instaweb::Str
string_util.cc:(.text._ZN12net_instaweb14StringToDoubleEPKcPd+0x14): undefined reference to `__strtod_internal'
pagespeed_automatic.a(132.ucnv.o.o): In function `pagespeed_ol_ucnv_conveucnv.c:(.text.ucnv_convertEx_46+0x6db): undefined reference to `__rawmemchr'
pagespeed_automatic.a(132.ucnv.o.o): In function `ucnv_internalConvert':
ucnv.c:(.text.ucnv_internalConvert+0x276): undefined reference to `__rawmemchr'
pagespeed_automatic.a(132.uloc.o.o): In function `pagespeed_ol_uloc_accep
uloc.c:(.text.uloc_acceptLanguageFromHTTP_46+0x214): undefined reference to `__strtod_internal'
uloc.c:(.text.uloc_acceptLanguageFromHTTP_46+0x452): undefined reference to `__strtod_internal'
pagespeed_automatic.a(132.uniset_props.o.o): In function `icu_46::Unicode
uniset_props.cpp:(.text._ZN6icu_4610UnicodeSet18applyPropertyAliasERKNS_13UnicodeStringES3_R10UErrorCode+0x35e): undefined reference to `__str
uniset_props.cpp:(.text._ZN6icu_4610UnicodeSet18applyPropertyAliasERKNS_13UnicodeStringES3_R10UErrorCode+0x462): undefined reference to `__str
```

It's worth finding how to make it compile and document it.

### PR DESCRIPTION
**Pull request by nberlee**
…inline), (directory structure organised for DockerHub build compatibility).

Alpine Linux is a security-oriented, lightweight Linux distribution based on musl libc and busy box. Alpine is therefor the most logical OS base for Docker Images.

Although it does not fix #1181 completely, it helps to overcome the problems of building the PSOL on Alpine,

### CODE REVIEW

**Comment by oschaaf** [comment]
Re: "Should we also go ahead & upgrade the trunk to png 1.6 to avoid having to do this patch?"
That would be nice, I'll have a go at that.

**Comment by oschaaf** [comment]
(actually, mps already has libpng 1.6 on the bleeding edge version: https://github.com/apache/incubator-pagespeed-mod/tree/master/third_party/libpng)

**Comment by oschaaf** [comment]
Maybe we should also link to the readme in https://github.com/apache/incubator-pagespeed-ngx/blob/master/README.md, and the docs (a new page over at https://www.modpagespeed.com/doc)?
